 export const productsdata =[{"id":1,"name":"Hatity","price":"$4.16","image":"https://robohash.org/minusmolestiaemagni.jpg?size=50x50&set=set1"},
{"id":2,"name":"Alpha","price":"$1.83","image":"https://robohash.org/iureeteveniet.jpg?size=50x50&set=set1"},
{"id":3,"name":"Cardguard","price":"$7.93","image":"https://robohash.org/earumaccusamusadipisci.jpg?size=50x50&set=set1"},
{"id":4,"name":"Zontrax","price":"$4.45","image":"https://robohash.org/optioducimusvoluptatibus.jpg?size=50x50&set=set1"},
{"id":5,"name":"Y-Solowarm","price":"$9.41","image":"https://robohash.org/noniustoest.jpg?size=50x50&set=set1"},
{"id":6,"name":"Transcof","price":"$8.10","image":"https://robohash.org/quosassumendaaut.jpg?size=50x50&set=set1"},
{"id":7,"name":"It","price":"$4.11","image":"https://robohash.org/omniseiusautem.jpg?size=50x50&set=set1"},
{"id":8,"name":"Home Ing","price":"$5.80","image":"https://robohash.org/voluptatemquibusdamsuscipit.jpg?size=50x50&set=set1"},
{"id":9,"name":"Lotlux","price":"$3.25","image":"https://robohash.org/siteaquererum.jpg?size=50x50&set=set1"},
{"id":10,"name":"Duobam","price":"$1.80","image":"https://robohash.org/aliaslaudantiumincidunt.jpg?size=50x50&set=set1"},
{"id":11,"name":"Daltfresh","price":"$7.95","image":"https://robohash.org/repellatinperferendis.jpg?size=50x50&set=set1"},
{"id":12,"name":"Otcom","price":"$6.64","image":"https://robohash.org/temporequisquod.jpg?size=50x50&set=set1"},
{"id":13,"name":"Voyatouch","price":"$1.45","image":"https://robohash.org/illositvoluptas.jpg?size=50x50&set=set1"},
{"id":14,"name":"It","price":"$9.82","image":"https://robohash.org/porroquaealiquam.jpg?size=50x50&set=set1"},
{"id":15,"name":"Job","price":"$10.00","image":"https://robohash.org/adquiamaiores.jpg?size=50x50&set=set1"},
{"id":16,"name":"Bytecard","price":"$0.06","image":"https://robohash.org/autemvelitvoluptas.jpg?size=50x50&set=set1"},
{"id":17,"name":"Alpha","price":"$9.94","image":"https://robohash.org/placeatasperioresprovident.jpg?size=50x50&set=set1"},
{"id":18,"name":"Matsoft","price":"$0.20","image":"https://robohash.org/animivelitqui.jpg?size=50x50&set=set1"},
{"id":19,"name":"Sonsing","price":"$5.74","image":"https://robohash.org/velitetqui.jpg?size=50x50&set=set1"},
{"id":20,"name":"Span","price":"$6.06","image":"https://robohash.org/quaeratanimioptio.jpg?size=50x50&set=set1"},
{"id":21,"name":"Holdlamis","price":"$6.22","image":"https://robohash.org/voluptatesfugaalias.jpg?size=50x50&set=set1"},
{"id":22,"name":"Home Ing","price":"$8.60","image":"https://robohash.org/suntcumut.jpg?size=50x50&set=set1"},
{"id":23,"name":"Treeflex","price":"$1.82","image":"https://robohash.org/repellatullamet.jpg?size=50x50&set=set1"},
{"id":24,"name":"Redhold","price":"$4.61","image":"https://robohash.org/rerumtemporeet.jpg?size=50x50&set=set1"},
{"id":25,"name":"Tin","price":"$6.12","image":"https://robohash.org/culpaestvoluptatibus.jpg?size=50x50&set=set1"},
{"id":26,"name":"Vagram","price":"$10.00","image":"https://robohash.org/repudiandaedignissimossint.jpg?size=50x50&set=set1"},
{"id":27,"name":"Daltfresh","price":"$0.00","image":"https://robohash.org/sitipsanecessitatibus.jpg?size=50x50&set=set1"},
{"id":28,"name":"Prodder","price":"$2.74","image":"https://robohash.org/ipsanecessitatibusmolestias.jpg?size=50x50&set=set1"},
{"id":29,"name":"Tres-Zap","price":"$1.33","image":"https://robohash.org/fugaisteaccusamus.jpg?size=50x50&set=set1"},
{"id":30,"name":"Temp","price":"$8.39","image":"https://robohash.org/reiciendisetpariatur.jpg?size=50x50&set=set1"}]
